<body>
<div id="wrap">
  <div id="top">
    <h2> <a href="index.html"><strong>VCFtools</strong></a></h2>
    <div id="menu">
      <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="http://sourceforge.net/projects/vcftools/">Sourceforge page</a></li>	
        <li><a href="examples.html">Examples &amp; Documentation</a></li>
        <li><a href="downloads.html" class="current">Downloads</a></li>
      </ul>
    </div>
  </div>
  <div id="content">
    
      <h2>Downloading through Sourceforge</h2>
      <p>There are two ways to download VCFtools.</p>
      <p>The <b>stable releases</b> can be downloaded from the project Sourceforge page here:</p>
      <p class="codebox" style="text-align: center;"><a href="https://sourceforge.net/projects/vcftools/files/">https://sourceforge.net/projects/vcftools/files/</a></p>
		<h2>Downloading with Subversion</h2>      
      <p>The <b>latest developmental version</b> can be downloaded through the subversion client. If subversion is installed, run the following command:</p>
      <p class="codebox" style="text-align: center;">svn checkout http://svn.code.sf.net/p/vcftools/code/trunk/ vcftools</p>
      <p>The above command is required to be run only once, for any subsequent updates run the following command from the vcftools directory:</p>
      <p class="codebox" style="text-align: center;">svn update</p>
    
    <div id="clear"></div>
  </div>
  <div id="footer">
    <p>Copyright 2014 &copy; VCFtools</p>
  </div>
</div>
</body>
</html>
