<body>
<div id="wrap">
  <div id="top">
    <h2> <a href="index.html"><strong>VCFtools</strong></a></h2>
    <div id="menu">
      <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="http://sourceforge.net/projects/vcftools/">Sourceforge page</a></li>	
        <li><a href="examples.html">Examples &amp; Documentation</a></li>
        <li><a href="downloads.html">Downloads</a></li>
      </ul>
    </div>
  </div>
  <div id="content">
    <div id="left">
      <h2>License</h2>
      <p>The program package is released under the GNU Lesser General Public License version 3.0 (LGPLv3).</p>
		<h2>Citing VCFtools</h2>
		<p>If you make use of VCFtools in your research, we would appreciate a citation of the following paper:<br><br>
		<a href="http://dx.doi.org/10.1093/bioinformatics/btr330"><i>The Variant Call Format and VCFtools</i></a>, 
		Petr Danecek, Adam Auton, Goncalo Abecasis, Cornelis A. Albers, Eric Banks, Mark A. DePristo, 
		Robert Handsaker, Gerton Lunter, Gabor Marth, Stephen T. Sherry, Gilean McVean, Richard Durbin 
		and 1000 Genomes Project Analysis Group, <b>Bioinformatics</b>, 2011
		</p>
		<h2>Authors</h2>
		<p>The program package is maintained and developed by:</p>
		<ul>
			<li><a href="http://www.adamauton.com/">Adam Auton</a> (C++ Module)
			<li>Petr Danecek (Perl Module, HTSlib)
			<li>Anthony Marcketta (C++ Module)</li>
		</ul>
    </div>
    <div id="right">
      <div class="box">
      	<h2>Posters</h2>
      	<ul>
      		<li><a href="VCF-poster.pdf">Original VCFtools poster</a></li>
      		<li><a href="vcf_poster_051513.pdf">VCFtools poster from May 2013</a></li>
      	</ul>
      </div></div>
    <div id="clear"></div>
  </div>
  <div id="footer">
    <p>Copyright 2014 &copy; VCFtools</p>
  </div>
</div>
</body>
</html>
