<body>
<div id="wrap">
  <div id="top">
    <h2> <a href="index.html"><strong>VCFtools</strong></a></h2>
    <div id="menu">
      <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="http://sourceforge.net/projects/vcftools/">Sourceforge page</a></li>	
        <li><a href="examples.html">Examples &amp; Documentation</a></li>
        <li><a href="downloads.html">Downloads</a></li>
      </ul>
    </div>
  </div>
  <div id="content">
    <div id="left">
      <h2>Useful Links</h2>
      <p>
      	<ul>
      		<li><a href="http://www.1000genomes.org/">1000 Genomes Project main page</a></li>
      		<li><a href="http://www.broadinstitute.org/gsa/wiki/index.php/The_Genome_Analysis_Toolkit">The Genome Analysis Toolkit</a> - The GATK Java package from the Broad includes a number of routines for generating and manipulating VCF file.</li>
      		<li><a href="http://samtools.sourceforge.net/" >Samtools</a> - a tool that can generate VCF files from SAM or BAM format files</li>
      		<li><a href="http://sourceforge.net/projects/samtools/files/tabix/">Tabix</a> - an indexing tool that is required for certain features in the PERL API.</li>
				<li><a href="https://github.com/ekg/vcflib">vcflib</a> - A simple C++ library for parsing and manipulating VCF files from Erik Garrison. </a></li>
				<li><a href="https://github.com/indapa/VcfPythonUtils">VcfPythonUtils</a> - Some Python utilities to work with VCF from Amit Indap. </a></li>
				<li><a href="https://github.com/AlistairNWard/vcfCTools">vcfCTools</a> - C++ implementation of vcfPytools from Alistair Ward.
      	</ul>
      </p>
    </div>
    <div id="clear"></div>
  </div>
  <div id="footer">
    <p>Copyright 2014 &copy; VCFtools</p>
  </div>
</div>
</body>
</html>
