<body>
<div id="wrap">
  <div id="top">
    <h2> <a href="index.html"><strong>VCFtools</strong></a></h2>
    <div id="menu">
      <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="http://sourceforge.net/projects/vcftools/">Sourceforge page</a></li>	
        <li><a href="examples.html">Examples &amp; Documentation</a></li>
        <li><a href="downloads.html">Downloads</a></li>
      </ul>
    </div>
  </div>
  <div id="content">
    <div id="left">
      <h2>VCF (Variant Call Format) specifications</h2>
		<p>The <b>newer</b> versions of the VCF v4.1, VCF v4.2, and BCF v2.1 specification documents can be found on <a href="https://github.com/samtools/hts-specs">github</a>. The <b>older</b> versions of the documents are hosted on the 1000 genomes wiki page.
		<ul>
	    	<li>VCF format v4.0: <a href="http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-40">1000 genomes wiki</a></li>
   	 	<li>VCF format v4.1: <a href="http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-41">1000 genomes wiki</a> | <a href="http://samtools.github.io/hts-specs/VCFv4.1.pdf">github</a> </li>
			<li>VCF format v4.2: <a href="http://www.1000genomes.org/wiki/analysis/variant-call-format/vcf-variant-call-format-version-42">1000 genomes wiki</a> | <a href="http://samtools.github.io/hts-specs/VCFv4.2.pdf">github</a> </li>
    		<li>BCF format v2.1: <a href="http://www.1000genomes.org/wiki/analysis/variant-call-format/bcf-binary-vcf-version-2">1000 genomes wiki</a> | <a href="http://samtools.github.io/hts-specs/BCFv2_qref.pdf">github</a></li>
    	</ul></p> 
		<p><a href="https://lists.sourceforge.net/lists/listinfo/vcftools-spec">VCFtools-spec</a> is a low traffic mailing list intended for VCF format related discussions, such as clarifications of the current format version or proposals of changes to the specification.</p>
	</div>
    <div id="clear"></div>
  </div>
  <div id="footer">
    <p>Copyright 2014 &copy; VCFtools</p>
  </div>
</div>
</body>
</html>
